version: '3.7'
services:
  mysql:
    image: mysql:latest
    restart: always
    volumes:
      - ./db/mysql/data:/var/lib/mysql
      - ./db/mysql/init:/docker-entrypoint-initdb.d
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: root
      TZ: Asia/Seoul
      MYSQL_DATABASE: myDb
      MYSQL_USER: swu
      MYSQL_PASSWORD: 1234
